/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { LlmAsJudgeMessageRole } from "./LlmAsJudgeMessageRole";

export const LlmAsJudgeMessage: core.serialization.ObjectSchema<
    serializers.LlmAsJudgeMessage.Raw,
    OpikApi.LlmAsJudgeMessage
> = core.serialization.object({
    role: LlmAsJudgeMessageRole,
    content: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    stringContent: core.serialization.property("string_content", core.serialization.boolean().optional()),
    structuredContent: core.serialization.property("structured_content", core.serialization.boolean().optional()),
});

export declare namespace LlmAsJudgeMessage {
    export interface Raw {
        role: LlmAsJudgeMessageRole.Raw;
        content: Record<string, unknown>;
        string_content?: boolean | null;
        structured_content?: boolean | null;
    }
}
