/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { LlmAsJudgeMessageWriteRole } from "./LlmAsJudgeMessageWriteRole";

export const LlmAsJudgeMessageWrite: core.serialization.ObjectSchema<
    serializers.LlmAsJudgeMessageWrite.Raw,
    OpikApi.LlmAsJudgeMessageWrite
> = core.serialization.object({
    role: LlmAsJudgeMessageWriteRole,
    content: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    stringContent: core.serialization.property("string_content", core.serialization.boolean().optional()),
    structuredContent: core.serialization.property("structured_content", core.serialization.boolean().optional()),
});

export declare namespace LlmAsJudgeMessageWrite {
    export interface Raw {
        role: LlmAsJudgeMessageWriteRole.Raw;
        content: Record<string, unknown>;
        string_content?: boolean | null;
        structured_content?: boolean | null;
    }
}
