/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { LlmAsJudgeMessagePublicRole } from "./LlmAsJudgeMessagePublicRole";

export const LlmAsJudgeMessagePublic: core.serialization.ObjectSchema<
    serializers.LlmAsJudgeMessagePublic.Raw,
    OpikApi.LlmAsJudgeMessagePublic
> = core.serialization.object({
    role: LlmAsJudgeMessagePublicRole,
    content: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    stringContent: core.serialization.property("string_content", core.serialization.boolean().optional()),
    structuredContent: core.serialization.property("structured_content", core.serialization.boolean().optional()),
});

export declare namespace LlmAsJudgeMessagePublic {
    export interface Raw {
        role: LlmAsJudgeMessagePublicRole.Raw;
        content: Record<string, unknown>;
        string_content?: boolean | null;
        structured_content?: boolean | null;
    }
}
